import {ProductType} from "../../src/types";

export const mockProductsUnfiltered: ProductType[] = [
    {
        "id": 31,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Aldwych Oxford",
        "color": "Chestnut",
        "avg_review": 4.48,
        "avg_monthly_sales": 22.8,
        "size": 12.5,
        "price": 259.58,
        "quantity": 36,
        "imageId": "product_brown_boots_2",
        "tag": "Featured"
    }, {
        "id": 32,
        "item_type": "shoe",
        "brand": "Bally",
        "name": "Sydney Wholecut Oxford",
        "color": "Chestnut",
        "avg_review": 4.98,
        "avg_monthly_sales": 112.0,
        "size": 9,
        "price": 259.51,
        "quantity": 3,
        "imageId": "product_black_shoe_4",
        "tag": null
    }, {
        "id": 33,
        "item_type": "boot",
        "brand": "Loake",
        "name": "Murphy Wingtip",
        "color": "Cognac",
        "avg_review": 4.25,
        "avg_monthly_sales": 38.1,
        "size": 10.5,
        "price": 258.34,
        "quantity": 28,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    }, {
        "id": 34,
        "item_type": "shoe",
        "brand": "Magnanni",
        "name": "Carlyle Plain-Toe Oxford",
        "color": "Grey",
        "avg_review": 4.35,
        "avg_monthly_sales": 63.6,
        "size": 8.5,
        "price": 117.3,
        "quantity": 5,
        "imageId": "product_black_shoe_4",
        "tag": "New Arrival"
    }, {
        "id": 35,
        "item_type": "shoe",
        "brand": "Paul Parkman",
        "name": "Cavanaugh Penny Loafer",
        "color": "Brown",
        "avg_review": 4.35,
        "avg_monthly_sales": 172.8,
        "size": 9.5,
        "price": 294.67,
        "quantity": 14,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    },
    {
        "id": 36,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Dexter Wingtip",
        "color": "Brown",
        "avg_review": 3.89,
        "avg_monthly_sales": 55.7,
        "size": 9.5,
        "price": 113.18,
        "quantity": 26,
        "imageId": "product_brown_shoe_1",
        "tag": "New Arrival"
    }, {
        "id": 37,
        "item_type": "shoe",
        "brand": "Gucci",
        "name": "Willoughby Cap-Toe Oxford",
        "color": "Tan",
        "avg_review": 4.35,
        "avg_monthly_sales": 86.7,
        "size": 9,
        "price": 216.94,
        "quantity": 10,
        "imageId": "product_brown_boots_1",
        "tag": "New Arrival"
    }, {
        "id": 38,
        "item_type": "shoe",
        "brand": "To Boot New York",
        "name": "Cavanaugh Penny Loafer",
        "color": "Black",
        "avg_review": 4.22,
        "avg_monthly_sales": 42.3,
        "size": 9,
        "price": 133.38,
        "quantity": 35,
        "imageId": "product_brown_shoe_1",
        "tag": null
    }, {
        "id": 39,
        "item_type": "shoe",
        "brand": "Stefano Bemer",
        "name": "Cambridge Wingtip",
        "color": "White",
        "avg_review": 5,
        "avg_monthly_sales": 77.6,
        "size": 7.5,
        "price": 246.06,
        "quantity": 36,
        "imageId": "product_brown_shoe_1",
        "tag": "Featured"
    }, {
        "id": 40,
        "item_type": "boot",
        "brand": "Stefano Bemer",
        "name": "Fifth Avenue Cap-Toe Oxford",
        "color": "White",
        "avg_review": 4.35,
        "avg_monthly_sales": 73.7,
        "size": 11.5,
        "price": 91.57,
        "quantity": 32,
        "imageId": "product_black_shoe_4",
        "tag": null
    }
]

export const mockProductsSortedByFeatured: ProductType[] = [
    {
        "id": 31,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Aldwych Oxford",
        "color": "Chestnut",
        "avg_review": 4.48,
        "avg_monthly_sales": 22.8,
        "size": 12.5,
        "price": 259.58,
        "quantity": 36,
        "imageId": "product_brown_boots_2",
        "tag": "Featured"
    },
    {
        "id": 39,
        "item_type": "shoe",
        "brand": "Stefano Bemer",
        "name": "Cambridge Wingtip",
        "color": "White",
        "avg_review": 5,
        "avg_monthly_sales": 77.6,
        "size": 7.5,
        "price": 246.06,
        "quantity": 36,
        "imageId": "product_brown_shoe_1",
        "tag": "Featured"
    },{
        "id": 32,
        "item_type": "shoe",
        "brand": "Bally",
        "name": "Sydney Wholecut Oxford",
        "color": "Chestnut",
        "avg_review": 4.98,
        "avg_monthly_sales": 112.0,
        "size": 9,
        "price": 259.51,
        "quantity": 3,
        "imageId": "product_black_shoe_4",
        "tag": null
    }, {
        "id": 33,
        "item_type": "boot",
        "brand": "Loake",
        "name": "Murphy Wingtip",
        "color": "Cognac",
        "avg_review": 4.25,
        "avg_monthly_sales": 38.1,
        "size": 10.5,
        "price": 258.34,
        "quantity": 28,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    }, {
        "id": 34,
        "item_type": "shoe",
        "brand": "Magnanni",
        "name": "Carlyle Plain-Toe Oxford",
        "color": "Grey",
        "avg_review": 4.35,
        "avg_monthly_sales": 63.6,
        "size": 8.5,
        "price": 117.3,
        "quantity": 5,
        "imageId": "product_black_shoe_4",
        "tag": "New Arrival"
    }, {
        "id": 35,
        "item_type": "shoe",
        "brand": "Paul Parkman",
        "name": "Cavanaugh Penny Loafer",
        "color": "Brown",
        "avg_review": 4.35,
        "avg_monthly_sales": 172.8,
        "size": 9.5,
        "price": 294.67,
        "quantity": 14,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    },
    {
        "id": 36,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Dexter Wingtip",
        "color": "Brown",
        "avg_review": 3.89,
        "avg_monthly_sales": 55.7,
        "size": 9.5,
        "price": 113.18,
        "quantity": 26,
        "imageId": "product_brown_shoe_1",
        "tag": "New Arrival"
    }, {
        "id": 37,
        "item_type": "shoe",
        "brand": "Gucci",
        "name": "Willoughby Cap-Toe Oxford",
        "color": "Tan",
        "avg_review": 4.35,
        "avg_monthly_sales": 86.7,
        "size": 9,
        "price": 216.94,
        "quantity": 10,
        "imageId": "product_brown_boots_1",
        "tag": "New Arrival"
    }, {
        "id": 38,
        "item_type": "shoe",
        "brand": "To Boot New York",
        "name": "Cavanaugh Penny Loafer",
        "color": "Black",
        "avg_review": 4.22,
        "avg_monthly_sales": 42.3,
        "size": 9,
        "price": 133.38,
        "quantity": 35,
        "imageId": "product_brown_shoe_1",
        "tag": null
    },{
        "id": 40,
        "item_type": "boot",
        "brand": "Stefano Bemer",
        "name": "Fifth Avenue Cap-Toe Oxford",
        "color": "White",
        "avg_review": 4.35,
        "avg_monthly_sales": 73.7,
        "size": 11.5,
        "price": 91.57,
        "quantity": 32,
        "imageId": "product_black_shoe_4",
        "tag": null
    }
]

export const mockProductsSortedByNewArrivals: ProductType[] = [
    {
        "id": 33,
        "item_type": "boot",
        "brand": "Loake",
        "name": "Murphy Wingtip",
        "color": "Cognac",
        "avg_review": 4.25,
        "avg_monthly_sales": 38.1,
        "size": 10.5,
        "price": 258.34,
        "quantity": 28,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    }, {
        "id": 34,
        "item_type": "shoe",
        "brand": "Magnanni",
        "name": "Carlyle Plain-Toe Oxford",
        "color": "Grey",
        "avg_review": 4.35,
        "avg_monthly_sales": 63.6,
        "size": 8.5,
        "price": 117.3,
        "quantity": 5,
        "imageId": "product_black_shoe_4",
        "tag": "New Arrival"
    }, {
        "id": 35,
        "item_type": "shoe",
        "brand": "Paul Parkman",
        "name": "Cavanaugh Penny Loafer",
        "color": "Brown",
        "avg_review": 4.35,
        "avg_monthly_sales": 172.8,
        "size": 9.5,
        "price": 294.67,
        "quantity": 14,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    },
    {
        "id": 36,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Dexter Wingtip",
        "color": "Brown",
        "avg_review": 3.89,
        "avg_monthly_sales": 55.7,
        "size": 9.5,
        "price": 113.18,
        "quantity": 26,
        "imageId": "product_brown_shoe_1",
        "tag": "New Arrival"
    }, {
        "id": 37,
        "item_type": "shoe",
        "brand": "Gucci",
        "name": "Willoughby Cap-Toe Oxford",
        "color": "Tan",
        "avg_review": 4.35,
        "avg_monthly_sales": 86.7,
        "size": 9,
        "price": 216.94,
        "quantity": 10,
        "imageId": "product_brown_boots_1",
        "tag": "New Arrival"
    },{
        "id": 31,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Aldwych Oxford",
        "color": "Chestnut",
        "avg_review": 4.48,
        "avg_monthly_sales": 22.8,
        "size": 12.5,
        "price": 259.58,
        "quantity": 36,
        "imageId": "product_brown_boots_2",
        "tag": "Featured"
    }, {
        "id": 32,
        "item_type": "shoe",
        "brand": "Bally",
        "name": "Sydney Wholecut Oxford",
        "color": "Chestnut",
        "avg_review": 4.98,
        "avg_monthly_sales": 112.0,
        "size": 9,
        "price": 259.51,
        "quantity": 3,
        "imageId": "product_black_shoe_4",
        "tag": null
    },{
        "id": 38,
        "item_type": "shoe",
        "brand": "To Boot New York",
        "name": "Cavanaugh Penny Loafer",
        "color": "Black",
        "avg_review": 4.22,
        "avg_monthly_sales": 42.3,
        "size": 9,
        "price": 133.38,
        "quantity": 35,
        "imageId": "product_brown_shoe_1",
        "tag": null
    }, {
        "id": 39,
        "item_type": "shoe",
        "brand": "Stefano Bemer",
        "name": "Cambridge Wingtip",
        "color": "White",
        "avg_review": 5,
        "avg_monthly_sales": 77.6,
        "size": 7.5,
        "price": 246.06,
        "quantity": 36,
        "imageId": "product_brown_shoe_1",
        "tag": "Featured"
    }, {
        "id": 40,
        "item_type": "boot",
        "brand": "Stefano Bemer",
        "name": "Fifth Avenue Cap-Toe Oxford",
        "color": "White",
        "avg_review": 4.35,
        "avg_monthly_sales": 73.7,
        "size": 11.5,
        "price": 91.57,
        "quantity": 32,
        "imageId": "product_black_shoe_4",
        "tag": null
    }
];

export const mockProductsSortedByBestSellers: ProductType[] = [
    {
        "id": 32,
        "item_type": "shoe",
        "brand": "Bally",
        "name": "Sydney Wholecut Oxford",
        "color": "Chestnut",
        "avg_review": 4.98,
        "avg_monthly_sales": 112.0,
        "size": 9,
        "price": 259.51,
        "quantity": 3,
        "imageId": "product_black_shoe_4",
        "tag": null
    },{
        "id": 35,
        "item_type": "shoe",
        "brand": "Paul Parkman",
        "name": "Cavanaugh Penny Loafer",
        "color": "Brown",
        "avg_review": 4.35,
        "avg_monthly_sales": 172.8,
        "size": 9.5,
        "price": 294.67,
        "quantity": 14,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    },
    {
        "id": 31,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Aldwych Oxford",
        "color": "Chestnut",
        "avg_review": 4.48,
        "avg_monthly_sales": 22.8,
        "size": 12.5,
        "price": 259.58,
        "quantity": 36,
        "imageId": "product_brown_boots_2",
        "tag": "Featured"
    },
    {
        "id": 33,
        "item_type": "boot",
        "brand": "Loake",
        "name": "Murphy Wingtip",
        "color": "Cognac",
        "avg_review": 4.25,
        "avg_monthly_sales": 38.1,
        "size": 10.5,
        "price": 258.34,
        "quantity": 28,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    }, {
        "id": 34,
        "item_type": "shoe",
        "brand": "Magnanni",
        "name": "Carlyle Plain-Toe Oxford",
        "color": "Grey",
        "avg_review": 4.35,
        "avg_monthly_sales": 63.6,
        "size": 8.5,
        "price": 117.3,
        "quantity": 5,
        "imageId": "product_black_shoe_4",
        "tag": "New Arrival"
    },{
        "id": 36,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Dexter Wingtip",
        "color": "Brown",
        "avg_review": 3.89,
        "avg_monthly_sales": 55.7,
        "size": 9.5,
        "price": 113.18,
        "quantity": 26,
        "imageId": "product_brown_shoe_1",
        "tag": "New Arrival"
    }, {
        "id": 37,
        "item_type": "shoe",
        "brand": "Gucci",
        "name": "Willoughby Cap-Toe Oxford",
        "color": "Tan",
        "avg_review": 4.35,
        "avg_monthly_sales": 86.7,
        "size": 9,
        "price": 216.94,
        "quantity": 10,
        "imageId": "product_brown_boots_1",
        "tag": "New Arrival"
    }, {
        "id": 38,
        "item_type": "shoe",
        "brand": "To Boot New York",
        "name": "Cavanaugh Penny Loafer",
        "color": "Black",
        "avg_review": 4.22,
        "avg_monthly_sales": 42.3,
        "size": 9,
        "price": 133.38,
        "quantity": 35,
        "imageId": "product_brown_shoe_1",
        "tag": null
    }, {
        "id": 39,
        "item_type": "shoe",
        "brand": "Stefano Bemer",
        "name": "Cambridge Wingtip",
        "color": "White",
        "avg_review": 5,
        "avg_monthly_sales": 77.6,
        "size": 7.5,
        "price": 246.06,
        "quantity": 36,
        "imageId": "product_brown_shoe_1",
        "tag": "Featured"
    }, {
        "id": 40,
        "item_type": "boot",
        "brand": "Stefano Bemer",
        "name": "Fifth Avenue Cap-Toe Oxford",
        "color": "White",
        "avg_review": 4.35,
        "avg_monthly_sales": 73.7,
        "size": 11.5,
        "price": 91.57,
        "quantity": 32,
        "imageId": "product_black_shoe_4",
        "tag": null
    }
];

export const mockProductsSortedByCustomerReviews: ProductType[] = [
    {
        "id": 39,
        "item_type": "shoe",
        "brand": "Stefano Bemer",
        "name": "Cambridge Wingtip",
        "color": "White",
        "avg_review": 5,
        "avg_monthly_sales": 77.6,
        "size": 7.5,
        "price": 246.06,
        "quantity": 36,
        "imageId": "product_brown_shoe_1",
        "tag": "Featured"
    },
    {
        "id": 32,
        "item_type": "shoe",
        "brand": "Bally",
        "name": "Sydney Wholecut Oxford",
        "color": "Chestnut",
        "avg_review": 4.98,
        "avg_monthly_sales": 112.0,
        "size": 9,
        "price": 259.51,
        "quantity": 3,
        "imageId": "product_black_shoe_4",
        "tag": null
    },
    {
        "id": 31,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Aldwych Oxford",
        "color": "Chestnut",
        "avg_review": 4.48,
        "avg_monthly_sales": 22.8,
        "size": 12.5,
        "price": 259.58,
        "quantity": 36,
        "imageId": "product_brown_boots_2",
        "tag": "Featured"
    },{
        "id": 34,
        "item_type": "shoe",
        "brand": "Magnanni",
        "name": "Carlyle Plain-Toe Oxford",
        "color": "Grey",
        "avg_review": 4.35,
        "avg_monthly_sales": 63.6,
        "size": 8.5,
        "price": 117.3,
        "quantity": 5,
        "imageId": "product_black_shoe_4",
        "tag": "New Arrival"
    }, {
        "id": 35,
        "item_type": "shoe",
        "brand": "Paul Parkman",
        "name": "Cavanaugh Penny Loafer",
        "color": "Brown",
        "avg_review": 4.35,
        "avg_monthly_sales": 172.8,
        "size": 9.5,
        "price": 294.67,
        "quantity": 14,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    },
    {
        "id": 37,
        "item_type": "shoe",
        "brand": "Gucci",
        "name": "Willoughby Cap-Toe Oxford",
        "color": "Tan",
        "avg_review": 4.35,
        "avg_monthly_sales": 86.7,
        "size": 9,
        "price": 216.94,
        "quantity": 10,
        "imageId": "product_brown_boots_1",
        "tag": "New Arrival"
    },
    {
        "id": 40,
        "item_type": "boot",
        "brand": "Stefano Bemer",
        "name": "Fifth Avenue Cap-Toe Oxford",
        "color": "White",
        "avg_review": 4.35,
        "avg_monthly_sales": 73.7,
        "size": 11.5,
        "price": 91.57,
        "quantity": 32,
        "imageId": "product_black_shoe_4",
        "tag": null
    },{
        "id": 33,
        "item_type": "boot",
        "brand": "Loake",
        "name": "Murphy Wingtip",
        "color": "Cognac",
        "avg_review": 4.25,
        "avg_monthly_sales": 38.1,
        "size": 10.5,
        "price": 258.34,
        "quantity": 28,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    },{
        "id": 38,
        "item_type": "shoe",
        "brand": "To Boot New York",
        "name": "Cavanaugh Penny Loafer",
        "color": "Black",
        "avg_review": 4.22,
        "avg_monthly_sales": 42.3,
        "size": 9,
        "price": 133.38,
        "quantity": 35,
        "imageId": "product_brown_shoe_1",
        "tag": null
    },{
        "id": 36,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Dexter Wingtip",
        "color": "Brown",
        "avg_review": 3.89,
        "avg_monthly_sales": 55.7,
        "size": 9.5,
        "price": 113.18,
        "quantity": 26,
        "imageId": "product_brown_shoe_1",
        "tag": "New Arrival"
    }
];

export const mockProductsSortedByPriceAscending: ProductType[] = [
    {
        "id": 35,
        "item_type": "shoe",
        "brand": "Paul Parkman",
        "name": "Cavanaugh Penny Loafer",
        "color": "Brown",
        "avg_review": 4.35,
        "avg_monthly_sales": 172.8,
        "size": 9.5,
        "price": 294.67,
        "quantity": 14,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    },
    {
        "id": 31,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Aldwych Oxford",
        "color": "Chestnut",
        "avg_review": 4.48,
        "avg_monthly_sales": 22.8,
        "size": 12.5,
        "price": 259.58,
        "quantity": 36,
        "imageId": "product_brown_boots_2",
        "tag": "Featured"
    },{
        "id": 32,
        "item_type": "shoe",
        "brand": "Bally",
        "name": "Sydney Wholecut Oxford",
        "color": "Chestnut",
        "avg_review": 4.98,
        "avg_monthly_sales": 112.0,
        "size": 9,
        "price": 259.51,
        "quantity": 3,
        "imageId": "product_black_shoe_4",
        "tag": null
    }, {
        "id": 33,
        "item_type": "boot",
        "brand": "Loake",
        "name": "Murphy Wingtip",
        "color": "Cognac",
        "avg_review": 4.25,
        "avg_monthly_sales": 38.1,
        "size": 10.5,
        "price": 258.34,
        "quantity": 28,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    },{
        "id": 39,
        "item_type": "shoe",
        "brand": "Stefano Bemer",
        "name": "Cambridge Wingtip",
        "color": "White",
        "avg_review": 5,
        "avg_monthly_sales": 77.6,
        "size": 7.5,
        "price": 246.06,
        "quantity": 36,
        "imageId": "product_brown_shoe_1",
        "tag": "Featured"
    },{
        "id": 37,
        "item_type": "shoe",
        "brand": "Gucci",
        "name": "Willoughby Cap-Toe Oxford",
        "color": "Tan",
        "avg_review": 4.35,
        "avg_monthly_sales": 86.7,
        "size": 9,
        "price": 216.94,
        "quantity": 10,
        "imageId": "product_brown_boots_1",
        "tag": "New Arrival"
    }, {
        "id": 38,
        "item_type": "shoe",
        "brand": "To Boot New York",
        "name": "Cavanaugh Penny Loafer",
        "color": "Black",
        "avg_review": 4.22,
        "avg_monthly_sales": 42.3,
        "size": 9,
        "price": 133.38,
        "quantity": 35,
        "imageId": "product_brown_shoe_1",
        "tag": null
    },{
        "id": 34,
        "item_type": "shoe",
        "brand": "Magnanni",
        "name": "Carlyle Plain-Toe Oxford",
        "color": "Grey",
        "avg_review": 4.35,
        "avg_monthly_sales": 63.6,
        "size": 8.5,
        "price": 117.3,
        "quantity": 5,
        "imageId": "product_black_shoe_4",
        "tag": "New Arrival"
    },{
        "id": 36,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Dexter Wingtip",
        "color": "Brown",
        "avg_review": 3.89,
        "avg_monthly_sales": 55.7,
        "size": 9.5,
        "price": 113.18,
        "quantity": 26,
        "imageId": "product_brown_shoe_1",
        "tag": "New Arrival"
    },{
        "id": 40,
        "item_type": "boot",
        "brand": "Stefano Bemer",
        "name": "Fifth Avenue Cap-Toe Oxford",
        "color": "White",
        "avg_review": 4.35,
        "avg_monthly_sales": 73.7,
        "size": 11.5,
        "price": 91.57,
        "quantity": 32,
        "imageId": "product_black_shoe_4",
        "tag": null
    }
];

export const mockProductsSortedByPriceDescending: ProductType[] = [
    {
        "id": 40,
        "item_type": "boot",
        "brand": "Stefano Bemer",
        "name": "Fifth Avenue Cap-Toe Oxford",
        "color": "White",
        "avg_review": 4.35,
        "avg_monthly_sales": 73.7,
        "size": 11.5,
        "price": 91.57,
        "quantity": 32,
        "imageId": "product_black_shoe_4",
        "tag": null
    },{
        "id": 36,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Dexter Wingtip",
        "color": "Brown",
        "avg_review": 3.89,
        "avg_monthly_sales": 55.7,
        "size": 9.5,
        "price": 113.18,
        "quantity": 26,
        "imageId": "product_brown_shoe_1",
        "tag": "New Arrival"
    },{
        "id": 34,
        "item_type": "shoe",
        "brand": "Magnanni",
        "name": "Carlyle Plain-Toe Oxford",
        "color": "Grey",
        "avg_review": 4.35,
        "avg_monthly_sales": 63.6,
        "size": 8.5,
        "price": 117.3,
        "quantity": 5,
        "imageId": "product_black_shoe_4",
        "tag": "New Arrival"
    },{
        "id": 38,
        "item_type": "shoe",
        "brand": "To Boot New York",
        "name": "Cavanaugh Penny Loafer",
        "color": "Black",
        "avg_review": 4.22,
        "avg_monthly_sales": 42.3,
        "size": 9,
        "price": 133.38,
        "quantity": 35,
        "imageId": "product_brown_shoe_1",
        "tag": null
    },{
        "id": 37,
        "item_type": "shoe",
        "brand": "Gucci",
        "name": "Willoughby Cap-Toe Oxford",
        "color": "Tan",
        "avg_review": 4.35,
        "avg_monthly_sales": 86.7,
        "size": 9,
        "price": 216.94,
        "quantity": 10,
        "imageId": "product_brown_boots_1",
        "tag": "New Arrival"
    },{
        "id": 39,
        "item_type": "shoe",
        "brand": "Stefano Bemer",
        "name": "Cambridge Wingtip",
        "color": "White",
        "avg_review": 5,
        "avg_monthly_sales": 77.6,
        "size": 7.5,
        "price": 246.06,
        "quantity": 36,
        "imageId": "product_brown_shoe_1",
        "tag": "Featured"
    },{
        "id": 33,
        "item_type": "boot",
        "brand": "Loake",
        "name": "Murphy Wingtip",
        "color": "Cognac",
        "avg_review": 4.25,
        "avg_monthly_sales": 38.1,
        "size": 10.5,
        "price": 258.34,
        "quantity": 28,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    },{
        "id": 32,
        "item_type": "shoe",
        "brand": "Bally",
        "name": "Sydney Wholecut Oxford",
        "color": "Chestnut",
        "avg_review": 4.98,
        "avg_monthly_sales": 112.0,
        "size": 9,
        "price": 259.51,
        "quantity": 3,
        "imageId": "product_black_shoe_4",
        "tag": null
    },{
        "id": 31,
        "item_type": "boot",
        "brand": "Alden",
        "name": "Aldwych Oxford",
        "color": "Chestnut",
        "avg_review": 4.48,
        "avg_monthly_sales": 22.8,
        "size": 12.5,
        "price": 259.58,
        "quantity": 36,
        "imageId": "product_brown_boots_2",
        "tag": "Featured"
    },{
        "id": 35,
        "item_type": "shoe",
        "brand": "Paul Parkman",
        "name": "Cavanaugh Penny Loafer",
        "color": "Brown",
        "avg_review": 4.35,
        "avg_monthly_sales": 172.8,
        "size": 9.5,
        "price": 294.67,
        "quantity": 14,
        "imageId": "product_black_shoe_2",
        "tag": "New Arrival"
    }
];